pharmacy/urls.py
from django.urls import path
from .views import home, medicine_list, add_medicine, order_medicine

urlpatterns = [
    path('', home, name='home'),
    path('medicines/', medicine_list, name='medicine_list'),
    path('medicines/add/', add_medicine, name='add_medicine'),
    path('medicines/order/', order_medicine, name='order_medicine'),
]

pharmacy_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pharmacy.urls')),
]

pharmacy/models.py
from django.db import models

class Medicine(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()

    def __str__(self):
        return self.name

class Order(models.Model):
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order of {self.quantity} {self.medicine.name}(s)"

pharmacy/forms.py
from django import forms
from .models import Medicine, Order

class MedicineForm(forms.ModelForm):
    class Meta:
        model = Medicine
        fields = ['name', 'description', 'price', 'stock']

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['medicine', 'quantity']

pharmacy/views.py
from django.shortcuts import render, redirect
from .models import Medicine, Order
from .forms import MedicineForm, OrderForm

def home(request):
    return render(request, 'pharmacy/home.html')

def medicine_list(request):
    medicines = Medicine.objects.all()
    return render(request, 'pharmacy/medicine_list.html', {'medicines': medicines})

def add_medicine(request):
    if request.method == 'POST':
        form = MedicineForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('medicine_list')
    else:
        form = MedicineForm()
    return render(request, 'pharmacy/add_medicine.html', {'form': form})

def order_medicine(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('medicine_list')
    else:
        form = OrderForm()
    return render(request, 'pharmacy/order_medicine.html', {'form': form})

pharmacy/templates/pharmacy/add_medicine.html
{% extends 'pharmacy/base.html' %}

{% block content %}
<section id="add-medicine">
    <div class="container">
        <h2>Add Medicine</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Name:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="id_description">Description:</label>
                {{ form.description }}
            </div>
            <div class="form-group">
                <label for="id_price">Price:</label>
                {{ form.price }}
            </div>
            <div class="form-group">
                <label for="id_stock">Stock:</label>
                {{ form.stock }}
            </div>
            <button type="submit">Add Medicine</button>
        </form>
    </div>
</section>
{% endblock %}

pharmacy/templates/pharmacy/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Pharmacy</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <div class="container">
            <h1>Online Pharmacy Management</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'medicine_list' %}">Medicines</a></li>
                    <li><a href="{% url 'add_medicine' %}">Add Medicine</a></li>
                    <li><a href="{% url 'order_medicine' %}">Order Medicine</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <main>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <footer>
        <div class="container">
            <p>&copy; 2024 Online Pharmacy Management</p>
        </div>
    </footer>
</body>
</html>

pharmacy/templates/pharmacy/home.html
{% extends 'pharmacy/base.html' %}

{% block content %}
<section id="home" class="hero">
    <div class="container">
        <h2>Welcome to the Online Pharmacy</h2>
        <p>Manage your medicines and orders efficiently.</p>
    </div>
</section>
{% endblock %}

pharmacy/templates/pharmacy/medicine_list.html
{% extends 'pharmacy/base.html' %}

{% block content %}
<section id="medicine-list">
    <div class="container">
        <h2>Medicine List</h2>
        <ul class="medicine-items">
            {% for medicine in medicines %}
            <li>
                <div class="medicine-item">
                    <h3>{{ medicine.name }}</h3>
                    <p>Description: {{ medicine.description }}</p>
                    <p>Price: RS {{ medicine.price }}</p>
                    <p>Stock: {{ medicine.stock }}</p>
                </div>
            </li>
            {% empty %}
            <li>No medicines found.</li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

pharmacy/templates/pharmacy/order_medicine.html
{% extends 'pharmacy/base.html' %}

{% block content %}
<section id="order-medicine">
    <div class="container">
        <h2>Order Medicine</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_medicine">Medicine:</label>
                {{ form.medicine }}
            </div>
            <div class="form-group">
                <label for="id_quantity">Quantity:</label>
                {{ form.quantity }}
            </div>
            <button type="submit">Place Order</button>
        </form>
    </div>
</section>
{% endblock %}